POST http://localhost:3003/api/bloglist 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRva2VudGVzdCIsImlkIjoiNjM5NzMzYzIyYzFiZmRkZDkzN2E2NDRmIiwiaWF0IjoxNjcwODUzNjYyfQ.AzW8EIUKfHLYUAJK2FHMuERQb2_VrRzFR8U5VNBv_qw

{
    "title": "token test",
    "author": "sajljk",
    "url": "dasdlijl",
    "likes": 1412
}

###
DELETE http://localhost:3003/api/bloglist/637fa1bee96c9636a9916ed5

###
PUT http://localhost:3003/api/bloglist/637f9b85c59475e6dafa25ef
Content-Type: application/json

{
    "likes": 123
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Tokentest",
    "name": "ASDASD",
    "password": "test"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Tokentest",
    "password": "test"
}

